WITH RankedCompanies AS (
    SELECT 
        YEAR,
        COMPANY_NAME_CLEAN,
        COUNT(*) AS `REGISTRATION_COUNT`,
        ROW_NUMBER() OVER (PARTITION BY YEAR ORDER BY COUNT(*) DESC) AS `RANK`
    FROM `processed_wh_info`
    WHERE YEAR >= 2019 
      AND COMPANY_NAME IS NOT NULL
    GROUP BY YEAR, COMPANY_NAME_CLEAN
)
SELECT 
    YEAR,
    COMPANY_NAME_CLEAN AS COMPANY_NAME,
    `REGISTRATION_COUNT`
FROM RankedCompanies
WHERE `RANK` <= 5 -- look up top 5 companies
ORDER BY YEAR ASC, `REGISTRATION_COUNT` DESC;