SELECT 
    YEAR,
    SIDO,
    COMPANY_NAME_CLEAN AS COMPANY_NAME,
    COUNT(*) AS `REGISTRATION_COUNT`
FROM `processed_wh_info`
WHERE COMPANY_NAME_CLEAN LIKE '%쿠팡%'
GROUP BY YEAR, SIDO, COMPANY_NAME_CLEAN
ORDER BY YEAR ASC, SIDO ASC;